In [2]:
import pandas as pd


In [3]:
pd.read_csv("marks.csv")

Name  Hours  Score
0  Vimal      3     30
1  Rahul      5     50
2   Abhi      2     20
3   Jake      1     10

In [4]:
dataset=pd.read_csv("marks.csv")

In [6]:
y=dataset["Score"]

In [7]:
x=dataset["Hours"]

In [8]:
type(x)

pandas.core.series.Series

In [9]:
x.values

array([3, 5, 2, 1], dtype=int64)

In [10]:
type(x.values)

numpy.ndarray

In [11]:
x.values.reshape(4,1)

array([[3],
       [5],
       [2],
       [1]], dtype=int64)

In [12]:
x=x.values.reshape(4,1)

In [13]:
x.ndim

2

In [15]:
from sklearn.linear_model import LinearRegression

In [16]:
model=LinearRegression()

In [22]:
model.fit(x,y)

LinearRegression()

In [23]:
model.coef_

array([10.])

In [25]:
model.rank_

1

In [26]:
import matplotlib

In [ ]:
matplotlib.