In [30]:
import pandas


In [31]:
dataset=pandas.read_csv("Student - Sheet1.csv")

In [32]:
dataset

Name  Hours Score
0  Vimal      3    30
1  Rahul      5    50
2   Abhi      2    20
3   Jake      1    10
4      X      8     ?

In [33]:
dataset["Score"][:4]

0    30
1    50
2    20
3    10
Name: Score, dtype: object

In [34]:
Y=dataset["Score"][:4]

In [35]:
X=dataset["Hours"][:4]

In [36]:
# import sklearn.linear_model


In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
model=LinearRegression()


In [39]:
# model.fit(X,Y)

In [40]:
type(X)

pandas.core.series.Series

In [41]:
import numpy

In [42]:
X= numpy.array(X)

In [43]:
Y=numpy.array(Y)

In [44]:
type(X)

numpy.ndarray

In [47]:
X=X.reshape(4,1)

In [48]:
Y=Y.reshape(4,1)

In [50]:
X.ndim

2

In [52]:
Y.ndim

2

In [55]:
mlmodel=model.fit(X,Y)

In [67]:
mlmodel.predict([[5]])

array([[50.]])

In [68]:
import joblib


In [69]:
joblib.dump(model,"mymarks.model")

['mymarks.model']

In [70]:
mymodel=joblib.load("mymarks.model")

In [71]:
mymodel.predict([[5]])

array([[50.]])

In [74]:
value=int(input("Enter your hours of study:"))

Enter your hours of study:4


In [75]:
mymodel.predict([[value]])

array([[40.]])