In [1]:
import cv2

In [18]:
cap=cv2.VideoCapture(0)

In [17]:
cap.release()

In [11]:
cap=cv2.VideoCapture("https://100.109.218.50:8080/video")

In [19]:
status,photo=cap.read()

In [15]:
cv2.imshow("hi",photo)

In [5]:
import numpy as np

In [16]:
a=np.array([
[1,10,100],
[2,20,200],
[3,30,300],
[4,40,400]
]
)

In [17]:
a

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400]])

In [18]:
a.shape

(4, 3)

In [19]:
a[1:3,1:3]

array([[ 20, 200],
       [ 30, 300]])

In [20]:
l=[
[1,10,100],
[2,20,200],
[3,30,300],
[4,40,400]
]

In [21]:
b=np.array(l)

In [22]:
b

array([[  1,  10, 100],
       [  2,  20, 200],
       [  3,  30, 300],
       [  4,  40, 400]])

In [23]:
a.ndim

2

In [4]:
photo

array([[[223, 179, 231],
        [223, 179, 230],
        [223, 180, 229],
        ...,
        [129,  96, 137],
        [133,  92, 132],
        [135,  93, 133]],

       [[225, 179, 231],
        [223, 178, 230],
        [222, 178, 230],
        ...,
        [134,  95, 139],
        [136,  94, 136],
        [138,  96, 139]],

       [[222, 178, 230],
        [222, 176, 229],
        [224, 177, 232],
        ...,
        [132,  95, 140],
        [135,  97, 144],
        [134,  96, 142]],

       ...,

       [[161, 173, 229],
        [136, 174, 235],
        [110, 174, 241],
        ...,
        [ 81,  80, 196],
        [ 83,  82, 194],
        [ 84,  83, 195]],

       [[135, 165, 244],
        [124, 168, 242],
        [114, 174, 241],
        ...,
        [ 85,  80, 201],
        [ 88,  81, 202],
        [ 88,  81, 202]],

       [[121, 168, 243],
        [117, 169, 242],
        [118, 174, 244],
        ...,
        [ 89,  77, 199],
        [ 92,  80, 202],
        [ 92,  80, 202]]

In [10]:
photo[:,:,0:2]=0

In [21]:
grayPhoto=cv2.cvtColor(photo,cv2.COLOR_BGR2GRAY)

In [22]:
cv2.imshow("hi",grayPhoto)

In [ ]:
cv2.imshow("hi",photo)